version: '3.0'
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=marketplace

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - prometheus-volume:/etc/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./first_rule.yml:/etc/prometheus/first_rule.yml
      - ./second_rule.yml:/etc/prometheus/second_rule.yml
    ports:
      - "9090:9090"
    networks:
      - metricas
  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - metricas

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.23.0
    restart: unless-stopped
    ports:
      - "9093:9093"
    networks:
      - metricas
    volumes:
      - ./alertmanager.yml:/etc/alertmanager.yml
      - alertmanager-data:/etc/alertmanager/data
    command: --config.file=/etc/alertmanager/alertmanager.yml --log.level=debug
volumes:
  grafana-volume:
  prometheus-volume:
  alertmanager-data:

networks:
  metricas:
    driver: bridge