version: '3.0'
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=marketplace

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - prometheus-volume:/etc/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
volumes:
  grafana-volume:
  prometheus-volume: