global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "first_rule.yml"
  - "second_rule.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'marketplace'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.1.11:8080' ]