groups:
  - name: marketplace
    rules:
      - alert: altaTaxaDeErrosNasRequisicoes
        expr: rate(http_server_requests_seconds_count{status="500"}[1m]) >= 0.2
        for: 1m
        labels:
          app: marketplace
          severity: critical
        annotations:
          title: Taxa de Erro Alta
          summary: A taxa de erro das requisições http estão com valores além do aceitável
          description: Mais de 50% das requisições http estão com erro